### ISSUE TITLE
Is it possible to delete objects currently?

### ISSUE THREAD

**Issue by fridgerator** [taylorfinnell/awscr-s3#10]
Would the form `@client` need to send a `delete` instead of `post` ?

**Comment by taylorfinnell** [comment]
Do you mean delete vie a presigned URL? I am not sure if S3 supports this, and currently the presigned URLs can only be generated for GET and PUT (https://github.com/taylorfinnell/awscr-s3/blob/master/src/awscr-s3/presigned/url.cr#L86). If you know that DELETE urls will work we can adjust this method to allow delete.

If you are referring to the code in #5, there is delete support for objects in that PR

**Comment by fridgerator** [comment]
I was referring to the code in that pr, looks good!

**Comment by taylorfinnell** [comment]
Cool! I have not merged that PR and have slowed down development as I am looking into generating a "client" via Amazon's JSON definitions of their APIs.
