### ISSUE TITLE
Automatically attach Content-Type header

### ISSUE THREAD

**Issue by timkendall** [taylorfinnell/awscr-s3#23]
It would be really nice if we implemented automatic `Content-Type` tagging based on file extension. See https://github.com/andrewrk/node-s3-client for example.

**Comment by taylorfinnell** [comment]
Specifically in the `FileUploader` class?

**Comment by timkendall** [comment]
Yessir. What do you think? I can probably submit a PR in the next day or so.

**Comment by taylorfinnell** [comment]
Thanks! That would be great! What happens if we guess wrong content type, does that cause issues?

**Comment by timkendall** [comment]
If it's based on file-extension there shouldn't be much of an issue. We don't have to support everything either. If we don't supply anything AWS just falls back to the default `binary/octet-stream` type.

We can also make this an optional feature or enabled by default.

**Comment by taylorfinnell** [comment]
Sounds good!
