### ISSUE TITLE
Wrong method name in docs

### ISSUE THREAD

**Issue by jwoertink** [taylorfinnell/awscr-s3#39]
In the docs, you have `create_bucket`, but looks like it's called `put_bucket`
https://github.com/taylorfinnell/awscr-s3/blob/master/README.md#create-a-bucket
https://github.com/taylorfinnell/awscr-s3/blob/master/src/awscr-s3/client.cr#L55

**Comment by taylorfinnell** [comment]
It should be changed to `put_bucket` to align more with the REST api
