### ISSUE TITLE
Uploading public file

### ISSUE THREAD

**Issue by jwoertink** [taylorfinnell/awscr-s3#40]
I have [this shard](https://github.com/jwoertink/sitemapper/blob/master/src/sitemapper/storage/aws_storage.cr#L24) where I upload a file, and I want it to have public read. I set these header options, but it doesn't seem to work for me. The object on S3 still doesn't have public read permissions. Is there something I'm missing?

**Comment by taylorfinnell** [comment]
Yea, I think that should work, not sure why it's not and I can dig into it a bit later. As a side note, I actually use your shard! Thank you for it! Here is how I implemented S3 storage for it. https://gist.github.com/taylorfinnell/d545a8237442e7e99b527fd7963e134c

Then in my kemal route
```
get "/sitemap.xml" do |env|
 env.redirect Sitemapper.new.most_recent_sitemap_url
end
```

Anyway, not what you're asking and I will try to look into the issue soon :)

**Comment by jwoertink** [comment]
oh nice! I actually did change my bucket policy just recently and it fixed it, though I was hoping just adding `{"x-amz-acl" => "public-read"}` would work. I'll give your implementation a try and see if that works better. Thanks!

**Comment by taylorfinnell** [comment]
I think this is good to close :)
