### ISSUE TITLE
Cant be used with the latest version of awscr-signer

### ISSUE THREAD

**Issue by fridgerator** [taylorfinnell/awscr-s3#6]
Since the version number in awscr-s3 shard.yml is locked at awscr-signer version 0.3.6,  awscr-signer version 0.3.8 cant be used.

could use something like `version: ~> 0.3.6` instead ?

**Comment by taylorfinnell** [comment]
Yes, that is a good idea! I will do it tonight :)

**Comment by taylorfinnell** [comment]
Should be fixed in master
