### ISSUE TITLE
host name sometimes needs region?

### ISSUE THREAD

**Issue by fridgerator** [taylorfinnell/awscr-s3#7]
I was trying to generate a pre-signed expiring url for an existing object and was getting a `PermanentRedirect` error: `The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.`

I edited [presigned/url.cr line 49](https://github.com/taylorfinnell/awscr-s3/blob/master/src/awscr-s3/presigned/url.cr#L49) and changed the `Host` header to `s3-#{@region}.amazonaws.com` and this worked.

I'm not sure if this is always needed or not.  Do you know anything about this?

**Comment by charlie-hadden** [comment]
I ran into a similar thing with this last night, but decided not to open an issue as my use case is slightly unique. Apologies if you'd rather this were posted as a separate issue, but I feel it is relevant.

I'm not actually using S3 but rather a [minio](https://minio.io/) docker instance meaning the amazonaws.com domain isn't relevant at all. For my case I switched to using awscr-signer alone as currently that's the only functionality I need. Having said that, I'm soon going to be at a point where using the client stuff from #5 would be very useful.

Would it be possible to make this value a configuration option which defaults to the amazon domain?

**Comment by taylorfinnell** [comment]
Thanks for finding this issue. Looks like it may need to use region specific urls. http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html

Perhaps it should default to using the region specific url but also support an optional override for a custom host?

Any thoughts welcome! I will take a deeper look soon.

**Comment by charlie-hadden** [comment]
That sounds like it would be perfect for my use case at least. Thanks for your work on this so far - it's already been hugely helpful!

**Comment by taylorfinnell** [comment]
Should be fixed in master

**Comment by fridgerator** [comment]
working great, thanks!
