### ISSUE TITLE
Release a new tag.

### ISSUE THREAD

**Issue by wout** [taylorfinnell/awscr-s3#78]
I've been experiencing version issues with the [shrine shard](https://github.com/jetrockets/shrine.cr). Locally, the latest tag is used (v0.7.0) while Travis seems to use the master branch. I don't know how and why, but specs fail locally, while they pass on Travis CI, and vice versa.

The issues I was having were related to http vs https calls using Webmock. As it turns out, the master uses https:

https://github.com/taylorfinnell/awscr-s3/blob/master/src/awscr-s3/http.cr#L103
https://github.com/taylorfinnell/awscr-s3/blob/master/src/awscr-s3/http.cr#L113

While the latest tag doesn't:

https://github.com/taylorfinnell/awscr-s3/blob/v0.7.0/src/awscr-s3/http.cr#L119
https://github.com/taylorfinnell/awscr-s3/blob/v0.7.0/src/awscr-s3/http.cr#L129

There was also an issue with `http.head` because master takes headers:

https://github.com/taylorfinnell/awscr-s3/blob/master/src/awscr-s3/http.cr#L57

While v0.7.0 doesn't:

https://github.com/taylorfinnell/awscr-s3/blob/v0.7.0/src/awscr-s3/http.cr#L73

Could you release a v0.8.0 with the latest changes? I've been banging my head against the wall while figuring out why those specs were failing :smile:

**Comment by taylorfinnell** [comment]
Yea, I have no idea why the specs fail locally on `master` they do for me too. I will try to sort it out and cut a release

**Comment by taylorfinnell** [comment]
Done!

**Comment by wout** [comment]
Thanks! That helps a lot. :smile:
