### ISSUE TITLE
Is there a way to upload a file and set to public?

### ISSUE THREAD

**Issue by ejstembler** [taylorfinnell/awscr-s3#82]
I see the Ruby gem equivalent lets you set `acl: 'public-read'` as an option when uploading.  Can you do something similar here?

If I try this, is doesn't work though:

```crystal
uploader = Awscr::S3::FileUploader.new(client)
headers = {
    "acl" => "public-read",
    "Content-Type" => "image/png",
    "Cache-Control" => "max-age=31536000",              
}
File.open(filename), "r") do |file|
  uploader.upload(bucket, obj_key, file, headers)
end
```

Any other ways to achive it?

**Comment by ejstembler** [comment]
Never mind.  I found your [examples/osx_screenshot_upload.cr](https://github.com/taylorfinnell/awscr-s3/blob/master/examples/osx_screenshot_upload.cr) example which uses a `Awscr::S3::Presigned::Form` and that worked!

**Comment by taylorfinnell** [comment]
The other option is to upload with the `FileUploader` and then use a presigned url to get the object. The `FileUploader` uses either `put_object` or multipart uploads behind the scene depending on file size. I am not sure if the acl can be set during those operations, if so maybe that should be supported

**Comment by taylorfinnell** [comment]
Looks like maybe the header needed to be `x-amz-acl` but I didn't test it
