### ISSUE TITLE
Cut new release to resolve awscr-signer deprecation warning

### ISSUE THREAD

**Issue by stephendolan** [taylorfinnell/awscr-s3#85]
First of all, thank you for the work you've done to produce such a wonderful library!

I'm using a couple of shards (https://github.com/jwoertink/sitemapper and https://github.com/jetrockets/shrine.cr) that use `~> 0.8.0` of this library, but with Crystal 0.35.1 are throwing a deprecation and with the nightly build are throwing errors.

It looks like this issue was already resolved here: https://github.com/taylorfinnell/awscr-signer/pull/51

Would it be possible to cut a release from the latest code in `master` so that other shards can safely upgrade to remove this warning?

**Comment by taylorfinnell** [comment]
Released 0.8.1
