### ISSUE TITLE
Objects using slashes no longer works

### ISSUE THREAD

**Issue by matthewmcgarvey** [taylorfinnell/awscr-s3#86]
https://github.com/taylorfinnell/awscr-s3/blob/d16e88438aff9989cdf05c8684fa8eb5e76799a8/src/awscr-s3/client.cr#L231

If I use slashes in the object name like `uploads/image.jpg` it gets turned into `uploads%2Fimage.jpg` which is unexpected. 

The method that does this is `URI.encode_www_form` but maybe you meant to use `URI.encode` instead? It leaves the slash, but I'm not entirely sure of the differences.

**Comment by matthewmcgarvey** [comment]
This issue should definitely be resolved before https://github.com/taylorfinnell/awscr-s3/issues/85

**Comment by taylorfinnell** [comment]
Possibly related to https://github.com/taylorfinnell/awscr-s3/issues/83?

I was able to repro it with

```
BUCKET = ENV["AWS_BUCKET"]
KEY    = ENV["AWS_KEY"]
SECRET = ENV["AWS_SECRET"]
REGION = ENV["AWS_REGION"]

client = Awscr::S3::Client.new(
  region: REGION,
  aws_access_key: KEY,
  aws_secret_key: SECRET
)

object = "hi/hey.jpg"

client.put_object(bucket: BUCKET, object: object, body: IO::Memory.new("Hey!"))

resp = client.get_object(bucket: BUCKET, object: object)
puts resp.body
```

I'll take a look soon

**Comment by taylorfinnell** [comment]
Yea I think it should be URI.encode, which won't encode reserved chars like `/`. 

https://github.com/crystal-lang/crystal/pull/7997

**Comment by BrucePerens** [comment]
Thank you for Awscr-S3. I am getting this bug, and can wait a month or so but it would be nice if you'd review the PR and make a release.
